**Listas y Tuplas**

In [6]:
# Creamos dos listas, una con valores y una vacía
lista_nombres = ["Laura", "Maria", "Belen", "Luz"]
lista_apellidos = []
print(lista_apellidos)

[]

In [7]:
lista_pasos = [15413, 15855, 22399, 19988, 12709, 19138, 22951, 22322, 24454, 28931, 16609, 18277, 12261, 25552, 11730, 
                17414, 14479, 26870, 16749, 21189, 19111, 16711, 15188, 16891, 19333, 29310, 11159, 24780, 16162, 27243, 
                25509, 12093, 27936, 26384, 21533, 10279, 21935, 14639, 25367, 14355, 20347, 10813, 24580, 10046, 18483, 
                10346, 16868, 24809, 17471, 27576, 12517, 25732, 14591, 11987, 17810, 20176, 16391, 16024, 16048, 28676, 
                25335, 24034, 15485, 18399, 17836, 14875, 27566, 18089, 23797, 22918, 14073, 29187, 12087, 19085, 17569,
                 18140, 17459, 28245, 15109, 16016, 28216, 28022, 25157, 18087, 16358, 14994, 10962, 19821, 21092, 12134, 
                 12009, 22892, 24083, 11765, 21264, 28741, 14182, 13915, 12436, 10187, 11471, 10577, 11485, 11433, 11658, 
                 20848, 17796, 22679, 23067, 21890, 28220, 29285, 16309, 29817, 28804, 11005, 15401, 23702, 16786, 14896, 
                 24178, 10373, 16763, 22812, 28614, 26935, 25784, 11107, 25799, 17822, 12292, 11369, 14136, 16532, 24141,
                  29349, 16447, 10077, 15471, 20883, 29682, 28964, 18774, 27953, 21658, 21828, 11803, 15622, 15064, 21091, 
                  14322, 13228, 28119, 27390, 21449, 27791, 21033, 20343, 20624, 23884, 11718, 21409, 18171, 18300, 29974, 
                  12643, 22086, 20843, 10437, 21713, 25663, 17602, 15319, 28865, 26728, 17051, 26404, 23716, 27192, 17778, 
                  25141, 11897, 10691, 24129, 21320, 18542, 21270, 12789, 25850, 20380, 14328, 21286, 28167, 29278, 22621, 
                  14658, 20507, 24664, 23576, 17824, 24224, 25997, 16528, 14958, 27292, 25185, 29302, 16500, 15896, 22053, 
                  14121, 25440, 25696, 21035, 21016, 10251, 22260, 12858, 20643, 22233, 27120, 28756, 21280, 21858, 16179, 
                  18970, 23784, 20594, 11523, 17052, 12248, 23102, 29652, 20581, 22300, 10141, 10804, 21182, 21917, 18006, 
                  23043, 19801, 23799, 12779, 22009, 12428, 13167, 11087, 12019, 13030, 23132, 24114, 11621, 15943, 14911, 
                  18857, 25109, 15980, 15324, 12708, 25638, 26344, 21300, 21780, 26383, 23641, 13083, 18088, 12258, 16420, 
                  15178, 21808, 18541, 18323, 19952, 28899, 24621, 14852, 28315, 11183, 20733, 29485, 27289, 14919, 16103, 
                  13592, 18814, 12244, 26812, 20472, 16635, 19761, 21187, 28498, 27037, 26134, 26325, 10239, 15529, 23709, 
                  28892, 25489, 27935, 20024, 22262, 16285, 18170, 19127, 24562, 25679, 29445, 18534, 12315, 20296, 21402, 
                  18490, 21050, 12527, 10716, 28409, 16710, 10650, 28504, 11451, 12253, 12896, 12195, 20017, 18136, 21939, 
                  24418, 17189, 26919, 28040, 15253, 28981, 29642, 15128, 27981, 19670, 20169, 28455, 18773, 25855, 27110, 
                  25800, 29737, 26784, 26341, 24567, 19608, 26170, 16374, 12422, 20258, 26122, 19105, 29678, 15851, 27466, 
                  26650, 24711, 19865, 25322, 11362]

In [9]:
print("El número de pasos es: ", lista_pasos)

El número de pasos es:  [15413, 15855, 22399, 19988, 12709, 19138, 22951, 22322, 24454, 28931, 16609, 18277, 12261, 25552, 11730, 17414, 14479, 26870, 16749, 21189, 19111, 16711, 15188, 16891, 19333, 29310, 11159, 24780, 16162, 27243, 25509, 12093, 27936, 26384, 21533, 10279, 21935, 14639, 25367, 14355, 20347, 10813, 24580, 10046, 18483, 10346, 16868, 24809, 17471, 27576, 12517, 25732, 14591, 11987, 17810, 20176, 16391, 16024, 16048, 28676, 25335, 24034, 15485, 18399, 17836, 14875, 27566, 18089, 23797, 22918, 14073, 29187, 12087, 19085, 17569, 18140, 17459, 28245, 15109, 16016, 28216, 28022, 25157, 18087, 16358, 14994, 10962, 19821, 21092, 12134, 12009, 22892, 24083, 11765, 21264, 28741, 14182, 13915, 12436, 10187, 11471, 10577, 11485, 11433, 11658, 20848, 17796, 22679, 23067, 21890, 28220, 29285, 16309, 29817, 28804, 11005, 15401, 23702, 16786, 14896, 24178, 10373, 16763, 22812, 28614, 26935, 25784, 11107, 25799, 17822, 12292, 11369, 14136, 16532, 24141, 29349, 16447, 10077, 15471, 20883, 29682, 28964, 18774, 27953, 21658, 21828, 11803, 15622, 15064, 21091, 14322, 13228, 28119, 27390, 21449, 27791, 21033, 20343, 20624, 23884, 11718, 21409, 18171, 18300, 29974, 12643, 22086, 20843, 10437, 21713, 25663, 17602, 15319, 28865, 26728, 17051, 26404, 23716, 27192, 17778, 25141, 11897, 10691, 24129, 21320, 18542, 21270, 12789, 25850, 20380, 14328, 21286, 28167, 29278, 22621, 14658, 20507, 24664, 23576, 17824, 24224, 25997, 16528, 14958, 27292, 25185, 29302, 16500, 15896, 22053, 14121, 25440, 25696, 21035, 21016, 10251, 22260, 12858, 20643, 22233, 27120, 28756, 21280, 21858, 16179, 18970, 23784, 20594, 11523, 17052, 12248, 23102, 29652, 20581, 22300, 10141, 10804, 21182, 21917, 18006, 23043, 19801, 23799, 12779, 22009, 12428, 13167, 11087, 12019, 13030, 23132, 24114, 11621, 15943, 14911, 18857, 25109, 15980, 15324, 12708, 25638, 26344, 21300, 21780, 26383, 23641, 13083, 18088, 12258, 16420, 15178, 21808, 18541, 18323, 19952, 28899, 24621, 14852, 28315, 11183, 20733, 29485, 27289, 14919, 16103, 13592, 18814, 12244, 26812, 20472, 16635, 19761, 21187, 28498, 27037, 26134, 26325, 10239, 15529, 23709, 28892, 25489, 27935, 20024, 22262, 16285, 18170, 19127, 24562, 25679, 29445, 18534, 12315, 20296, 21402, 18490, 21050, 12527, 10716, 28409, 16710, 10650, 28504, 11451, 12253, 12896, 12195, 20017, 18136, 21939, 24418, 17189, 26919, 28040, 15253, 28981, 29642, 15128, 27981, 19670, 20169, 28455, 18773, 25855, 27110, 25800, 29737, 26784, 26341, 24567, 19608, 26170, 16374, 12422, 20258, 26122, 19105, 29678, 15851, 27466, 26650, 24711, 19865, 25322, 11362]

In [10]:
# Creamos dos variables que usen la función min y max
minimo = min(lista_pasos)
maximo = max(lista_pasos)

In [12]:
print("Pasos mínimos",minimo)
print("Pasos máximos",maximo)

Pasos mínimos 10046
Pasos máximos 29974

In [13]:
frutas = ["mora", "lulo","mango","uva"]
#voy a exaxaminar si mi lista de frutas tiene pera y lulo
"pera" in frutas

False

In [14]:
#voy a exaxaminar si mi lista de frutas tiene lulo
"lulo" in frutas

True

In [8]:
print(lista_pasos)

[15413, 15855, 22399, 19988, 12709, 19138, 22951, 22322, 24454, 28931, 16609, 18277, 12261, 25552, 11730, 17414, 14479, 26870, 16749, 21189, 19111, 16711, 15188, 16891, 19333, 29310, 11159, 24780, 16162, 27243, 25509, 12093, 27936, 26384, 21533, 10279, 21935, 14639, 25367, 14355, 20347, 10813, 24580, 10046, 18483, 10346, 16868, 24809, 17471, 27576, 12517, 25732, 14591, 11987, 17810, 20176, 16391, 16024, 16048, 28676, 25335, 24034, 15485, 18399, 17836, 14875, 27566, 18089, 23797, 22918, 14073, 29187, 12087, 19085, 17569, 18140, 17459, 28245, 15109, 16016, 28216, 28022, 25157, 18087, 16358, 14994, 10962, 19821, 21092, 12134, 12009, 22892, 24083, 11765, 21264, 28741, 14182, 13915, 12436, 10187, 11471, 10577, 11485, 11433, 11658, 20848, 17796, 22679, 23067, 21890, 28220, 29285, 16309, 29817, 28804, 11005, 15401, 23702, 16786, 14896, 24178, 10373, 16763, 22812, 28614, 26935, 25784, 11107, 25799, 17822, 12292, 11369, 14136, 16532, 24141, 29349, 16447, 10077, 15471, 20883, 29682, 28964, 18774, 27953, 21658, 21828, 11803, 15622, 15064, 21091, 14322, 13228, 28119, 27390, 21449, 27791, 21033, 20343, 20624, 23884, 11718, 21409, 18171, 18300, 29974, 12643, 22086, 20843, 10437, 21713, 25663, 17602, 15319, 28865, 26728, 17051, 26404, 23716, 27192, 17778, 25141, 11897, 10691, 24129, 21320, 18542, 21270, 12789, 25850, 20380, 14328, 21286, 28167, 29278, 22621, 14658, 20507, 24664, 23576, 17824, 24224, 25997, 16528, 14958, 27292, 25185, 29302, 16500, 15896, 22053, 14121, 25440, 25696, 21035, 21016, 10251, 22260, 12858, 20643, 22233, 27120, 28756, 21280, 21858, 16179, 18970, 23784, 20594, 11523, 17052, 12248, 23102, 29652, 20581, 22300, 10141, 10804, 21182, 21917, 18006, 23043, 19801, 23799, 12779, 22009, 12428, 13167, 11087, 12019, 13030, 23132, 24114, 11621, 15943, 14911, 18857, 25109, 15980, 15324, 12708, 25638, 26344, 21300, 21780, 26383, 23641, 13083, 18088, 12258, 16420, 15178, 21808, 18541, 18323, 19952, 28899, 24621, 14852, 28315, 11183, 20733, 29485, 27289, 14919, 16103, 13592, 18814, 12244, 26812, 20472, 16635, 19761, 21187, 28498, 27037, 26134, 26325, 10239, 15529, 23709, 28892, 25489, 27935, 20024, 22262, 16285, 18170, 19127, 24562, 25679, 29445, 18534, 12315, 20296, 21402, 18490, 21050, 12527, 10716, 28409, 16710, 10650, 28504, 11451, 12253, 12896, 12195, 20017, 18136, 21939, 24418, 17189, 26919, 28040, 15253, 28981, 29642, 15128, 27981, 19670, 20169, 28455, 18773, 25855, 27110, 25800, 29737, 26784, 26341, 24567, 19608, 26170, 16374, 12422, 20258, 26122, 19105, 29678, 15851, 27466, 26650, 24711, 19865, 25322, 11362]

In [20]:
# Vamos a localizar el valor de una posición concreta de la lista
print("El tercer número de pasos que tenemos en la lista es",lista_pasos[2])

El tercer número de pasos que tenemos en la lista es 22399

In [9]:
# Recuento del número total de valores en la lista
len(lista_pasos)

365

In [25]:
# Tenemos 365 días de pasos, vamos a ver cuántos pasos hicimos el último día
print(lista_pasos[len(lista_pasos)-1])
print(lista_pasos[364])

11362
11362

In [35]:
# También podemos ponerlo sin print si hay UNA SOLA LÍNEA

(lista_pasos[364])

11362

In [30]:
letras = ["A", "J", "Z", "B", "R"]
letras

['A', 'J', 'Z', 'B', 'R']

In [28]:
letras[3]

'B'

In [31]:
letras[1:4]

['J', 'Z', 'B']

In [44]:
# Copiamos la lista
letras2 = letras.copy()
print(letras)
print(letras2)

['A', 'J', 'Z', 'B', 'R']
['A', 'J', 'Z', 'B', 'R']

**Las tuplas, a diferencia de las listas, no se pueden modificar. Podemos convertir una tupla en lista, editarla, y volver a convertirla en tupla (NO modificable).**

In [49]:
# Creamos una tupla
tupla_nombres = ("Lola", "Paula")

# Cambiamos tupla a lista
lista_nombres = list(tupla_nombres)

print(lista_nombres)

['Lola', 'Paula']

In [52]:
# Añadimos un nombre más a la lista eligiendo en qué posición, por ello usamos insert
lista_nombres.insert(2,"Andrea")
print(lista_nombres)

['Lola', 'Paula', 'Andrea', 'Andrea']